
-- insert admin (username a, password aa)
INSERT INTO IWUser (id, enabled, roles, username, password)
VALUES (1, TRUE, 'ADMIN,USER', 'a',
    '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');
INSERT INTO IWUser (id, enabled, roles, username, password)
VALUES (2, TRUE, 'USER', 'b',
    '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W');

-- start id numbering from a value that is larger than any assigned above
ALTER SEQUENCE 'PUBLIC'.'GEN' RESTART WITH 1024;


INSERT INTO Guia (id, titulo, autor, fecha, puntuacion, campeon, posiciones, etiquetas, elo, hechizos, items, texto) VALUES 
(1, 'Guia suspicaz', 'David Alfonso', '2024-01-02', 9.8, 'aatrox', 'top', 'campeon', 'diamante', 'flash', '4010 3348 2419 2152 2150', 'texto generico'),
(2, 'Guia excelente', 'Laura Lopez', '2021-05-01', 9.0, 'jhin', 'bot', 'campeon', 'platino', 'ignite', '4010 3348 2419 2152 2150', 'texto generico'),
(3, 'Guia vers�til', 'Carlos Rodriguez', '2023-12-02', 8.5, 'leona', 'sup', 'campeon', 'oro', 'teleport', '4010 3348 2419 2152 2150', 'texto generico'),
(4, 'Gu�a t�ctica para principiantes', 'Ana Mart�nez', '2023-05-02', 8.7, 'Annie', 'mid', 'campeon',  'plata', 'Teleport Flash', '4010 3348 2419 2152 2150', 'Consejos y estrategias esenciales para jugadores novatos.'),
(5, 'Dominando el juego con Jinx', 'Pablo Gonz�lez', '2023-10-15', 9.5, 'Jinx', 'bot', 'campeon', 'diamante', 'Flash Heal', '4010 3348 2419 2152 2150', 'Aprende a jugar como un profesional con la campeona Jinx.'),
(6, 'Guia suspicaz', 'David Alfonso', '2023-12-12', 9.8, 'aatrox', 'top', 'campeon', 'diamante', 'flash', '4010 3348 2419 2152 2150', 'texto generico'),
(7, 'Guia excelente', 'Laura Lopez', '2023-12-15', 9.0, 'jhin', 'bot', 'campeon', 'platino', 'ignite', '4010 3348 2419 2152 2150', 'texto generico'),
(8, 'Guia vers�til', 'Carlos Rodriguez', '2023-12-15', 8.5, 'leona', 'sup','campeon', 'oro', 'teleport', '4010 3348 2419 2152 2150', 'texto generico');




INSERT INTO Campeon (nombre, posiciones) VALUES 
('aatrox', 'top'),
('ahri', 'mid'),
('akali', 'mid'),
('akshan', 'top mid'),
('alistar', 'sup'),
('amumu', 'jgl sup'),
('anivia', 'mid'),
('annie', 'mid sup'),
('aphelios', 'bot'),
('ashe', 'bot sup'),
('aurelionsol', 'mid'),
('azir', 'mid'),
('bard', 'sup'),
('belveth', 'jgl'),
('blitzcrank', 'sup'),
('brand', 'jgl sup'),
('braum', 'sup'),
('briar', 'jgl'),
('caitlyn', 'bot'),
('camille', 'top'),
('cassiopeia', 'mid'),
('chogath', 'top jgl mid bot sup'),
('corki', 'mid'),
('darius', 'top'),
('diana', 'jgl mid'),
('drmundo', 'top'),
('draven', 'bot'),
('ekko', 'mid'),
('elise', 'jgl'),
('evelynn', 'jgl'),
('ezreal', 'bot'),
('fiddlesticks', 'jgl'),
('fiora', 'top'),
('fizz', 'mid'),
('galio', 'mid sup'),
('gangplank', 'top'),
('garen', 'top'),
('gnar', 'top'),
('gragas', 'top jgl mid sup'),
('graves', 'top jgl'),
('gwen', 'top jgl'),
('hecarim', 'jgl'),
('heimerdinger', 'mid sup'),
('hwei', 'mid sup'),
('illaoi', 'top'),
('irelia', 'top mid'),
('ivern', 'jgl'),
('janna', 'sup'),
('jarvaniv', 'top jgl'),
('jax', 'top jgl'),
('jayce', 'top mid'),
('jhin', 'bot'),
('jinx', 'bot'),
('kaisa', 'bot'),
('kalista', 'bot'),
('karma', 'top mid sup'),
('karthus', 'jgl bot'),
('kassadin', 'mid'),
('katarina', 'mid'),
('kayle', 'top mid'),
('kayn', 'jgl'),
('kennen', 'top'),
('khazix', 'jgl'),
('kindred', 'jgl'),
('kled', 'top'),
('kogmaw', 'bot'),
('ksante', 'top'),
('leblanc', 'mid'),
('leesin', 'jgl'),
('leona', 'sup'),
('lillia', 'jgl'),
('lissandra', 'mid'),
('lucian', 'bot'),
('lulu', 'sup'),
('lux', 'mid'),
('malphite', 'top'),
('malzahar', 'mid'),
('maokai', 'jgl sup'),
('masteryi', 'jgl'),
('milio', 'sup'),
('missfortune', 'bot'),
('mordekaiser', 'top'),
('morgana', 'sup'),
('naafiri', 'jgl'),
('nami', 'sup'),
('nasus', 'top'),
('nautilus', 'sup'),
('neeko', 'jgl mid'),
('nidalee', 'jgl'),
('nilah', 'bot'),
('nocturne', 'jgl'),
('nunu', 'jgl'),
('olaf', 'top jgl'),
('orianna', 'mid'),
('ornn', 'top'),
('pantheon', 'top jgl mid sup'),
('poppy', 'top jgl sup'),
('pyke', 'sup'),
('qiyana', 'jgl mid'),
('quinn', 'top'),
('rakan', 'sup'),
('rammus', 'jgl'),
('reksai', 'jgl'),
('rell', 'jgl sup'),
('renata glasc', 'sup'),
('renekton', 'top'),
('rengar', 'top jgl'),
('riven', 'top'),
('rumble', 'top jgl'),
('ryze', 'mid'),
('samira', 'bot'),
('sejuani', 'jgl'),
('senna', 'bot sup'),
('seraphine', 'mid sup'),
('sett', 'top sup'),
('shaco', 'jgl'),
('shen', 'top'),
('shyvana', 'jgl'),
('singed', 'top'),
('sion', 'top'),
('sivir', 'bot'),
('skarner', 'jgl'),
('smolder', 'bot'),
('sona', 'sup'),
('soraka', 'sup'),
('swain', 'mid bot sup'),
('sylas', 'jgl mid'),
('syndra', 'mid'),
('tahmkench', 'top sup'),
('taliyah', 'jgl mid'),
('talon', 'jgl mid'),
('taric', 'sup'),
('teemo', 'top'),
('thresh', 'sup'),
('tristana', 'bot'),
('trundle', 'top jgl'),
('tryndamere', 'top'),
('twistedfate', 'mid'),
('twitch', 'bot'),
('udyr', 'jgl'),
('urgot', 'top'),
('varus', 'bot'),
('vayne', 'bot'),
('veigar', 'mid bot'),
('velkoz', 'mid'),
('vex', 'mid'),
('vi', 'jgl'),
('viego', 'jgl'),
('viktor', 'mid'),
('vladimir', 'mid'),
('volibear', 'top jgl'),
('warwick', 'top jgl'),
('monkeyking', 'top jgl'),
('xayah', 'bot'),
('xerath', 'sup'),
('xinzhao', 'jgl'),
('yasuo', 'top mid bot'),
('yone', 'top mid'),
('yorick', 'top'),
('yuumi', 'sup'),
('zac', 'jgl'),
('zed', 'jgl mid'),
('zeri', 'bot'),
('ziggs', 'mid bot'),
('zilean', 'sup'),
('zoe', 'mid'),
('zyra', 'sup');

INSERT INTO Hechizo (nombre) VALUES 
('flash'),
('ghost'),
('ignite'),
('teleport'),
('heal'),
('exhaust'),
('barrier'),
('clarity'),
('cleanse'),
('snowball'),
('smite'),
('red-smite'),
('green-smite'),
('blue-smite');


INSERT INTO Item (id, nombre, clase) VALUES 
('1083.png', 'Preferencia',''),
('1055.png', 'Espada de Doran',''),
('1056.png', 'Anillo de Doran',''),
('1054.png', 'Escudo de Doran',''),
('1102.png', 'Cria de caminabrisas',''),
('1103.png', 'Brote de Brincamontes',''),
('4015.png', 'Perplejidad',''),
('1101.png', 'Cachorro de carga ignea',''),
('3070.png', 'Lagrima de la diosa',''),
('3865.png', 'Atlas Mundial',''),
('2055.png', 'Guardian de control',''),
('2033.png', 'Pocion de corrupcion',''),
('2138.png', 'Elixir de hierro',''),
('2139.png', 'Elixir de Brujeria',''),
('2140.png', 'Elixir de Colera',''),
('2003.png', 'Pocion de Vida',''),
('2031.png', 'Pocion reutilizable',''),
('3363.png', 'Vision lejana modificada',''),
('3364.png', 'Lente de Oraculo',''),
('3340.png', 'Guardian de Vision',''),
('3006.png', 'Grebas de berserker',''),
('3009.png', 'Botas de rapidez',''),
('1001.png', 'Botas',''),
('3158.png', 'Botas Jonias de la lucidez',''),
('3111.png', 'Botas de Mercurio',''),
('3117.png', 'Botas de Movilidad',''),
('3047.png', 'Botas Blindadas',''),
('3020.png', 'Botas de Hechicero',''),
('1052.png', 'Tomo Amplificador',''),
('1038.png', 'Espadon',''),
('1026.png', 'Vara Explosiva',''),
('1018.png', 'Capa de Agilidad',''),
('1029.png', 'Armadura de tela',''),
('1042.png', 'Daga',''),
('1082.png', 'Sello oscuro',''),
('1004.png', 'Amuleto de las hadas',''),
('2022.png', 'Mota Brillante',''),
('1036.png', 'Espada larga',''),
('1058.png', 'Vara Innecesariamente Grande',''),
('1033.png', 'Manto de anulacion de magia',''),
('1037.png', 'Pico',''),
('1006.png', 'Perla de rejuvenecimiento',''),
('1028.png', 'Cristal de rubi',''),
('1027.png', 'Cristal de Zafiro',''),
('3113.png', 'Brisa de eter',''),
('6660.png', 'Rescoldo de Bami',''),
('4642.png', 'Espejo de cristal de Bandle',''),
('4630.png', 'Joya de la plaga',''),
('3076.png', 'chaleco de zarzas',''),
('3803.png', 'Catalizador de eones',''),
('3133.png', 'Martillo de guerra de Caulfield',''),
('1031.png', 'Chaleco de cadenas',''),
('3801.png', 'Brazal cristalino',''),
('3123.png', 'Llamada del verdugo',''),
('3108.png', 'Codice diabolico',''),
('3114.png', 'Idolo prohibido',''),
('1011.png', 'Cinturon del gigante',''),
('3024.png', 'Broquel glacial',''),
('3147.png', 'Disfraz encantado',''),
('3051.png', 'Hacha hogareña',''),
('3155.png', 'Sorbemaleficios',''),
('3145.png', 'Alternador hextech',''),
('3067.png', 'Gema avivadora',''),
('2015.png', 'Fragmento de kircheis',''),
('3035.png', 'Ultimas palabras',''),
('4003.png', 'Salvavidas',''),
('3802.png', 'Capitulo perdido',''),
('1057.png', 'Capa negatron',''),
('6670.png', 'Carcaj del mediodia',''),
('3916.png', 'Orbe del olvido',''),
('3044.png', 'Bacteriofago',''),
('3140.png', 'Cinturon negro',''),
('6690.png', 'Rectrice',''),
('1043.png', 'Arco curvo',''),
('2420.png', 'brazalete de la buscadora',''),
('3134.png', 'Daga dentada',''),
('3057.png', 'Brillo',''),
('3211.png', 'Habito del espectro',''),
('2019.png', 'Sello de acero',''),
('2020.png', 'Embrutecedor',''),
('3077.png', 'Tiamat',''),
('2021.png', 'Tuneladora',''),
('1053.png', 'Cetro vampirico',''),
('4632.png', 'Barrera Frondosa',''),
('3082.png', 'Malla del guardian',''),
('4638.png', 'Piedra de guardianes atenta',''),
('3066.png', 'Armadura lunar alada',''),
('3086.png', 'Fervor',''),
('8020.png', 'Mascara Abisal','Tanque'),
('8001.png', 'Cadenas de Anatema','Tanque'),
('3003.png', 'Baston del arcangel','Mago'),
('3504.png', 'Incensario ardiente','Soporte'),
('6696.png', 'Arco axiomatico','Asesino'),
('3102.png', 'Amuleto de las hadas','Mago'),
('3071.png', 'Cuchilla obsidiana','Bruiser'),
('3153.png', 'Hoja del rey arruinado','Bruiser'),
('3877.png', 'Tonada sanguina','Soporte'),
('3072.png', 'Sanguinaria','Tirador'),
('3869.png', 'Detraccion Celestial','Soporte'),
('6609.png', 'Mecanoespada punki','Tirador'),
('4629.png', 'Impulso cosmico','Mago'),
('3137.png', 'Florescencia sepulcral','Mago'),
('6621.png', 'Al alba','Mago'),
('3742.png', 'Coraza del muerto','Tanque'),
('6333.png', 'Baile de la muerte','Bruiser'),
('3128.png', 'Tenaza de la muerte ignea','Mago'),
('3870.png', 'Tejesueños','Soporte'),
('6620.png', 'Gritos de la ciudad agonica','Soporte'),
('6692.png', 'Eclipse','Asesino'),
('3814.png', 'Filo de la noche','Asesino'),
('3508.png', 'Segador de esencia','Tirador'),
('3073.png', 'Experimento de hexarmadura','Bruiser'),
('3121.png', 'Armadura de General invierno','Tanque'),
('4401.png', 'Fuerza de la naturaleza','Tanque'),
('3110.png', 'Corazon de hielo','Tanque'),
('3026.png', 'Angel de la guarda','Tirador'),
('3124.png', 'Espada de Guinsoo','Tirador'),
('3084.png', 'Corazon de acero','Tanque'),
('3146.png', 'Sable-pistola Hextech','Bruiser'),
('3152.png', 'Cinturon hextech','Mago'),
('6664.png', 'Fulgor vano','Tanque'),
('4628.png', 'Precision infalible','Mago'),
('6697.png', 'Soberbia','Asesino'),
('3181.png', 'Rompecascos','Bruiser'),
('6662.png', 'Guantelete de hielo','Tanque'),
('6673.png', 'Arcoescudo Inmortal','Bruiser'),
('4005.png', 'Mandato imperial','Soporte'),
('3031.png', 'Filo Infinito','Tirador'),
('6665.png', 'JakSho, el Proteico','Tanque'),
('2504.png', 'Rookern kaenico','Tanque'),
('3109.png', 'Promesa del caballero','Soporte'),
('6672.png', 'Matador de Krakens','Tirador'),
('6653.png', 'Tormento de Liandry','Mago'),
('3100.png', 'Perdicion de Liche','Mago'),
('3190.png', 'Medallon de Solari','Soporte'),
('3036.png', 'Recuerdos de Lord Dominik','Tirador'),
('6655.png', 'Compañero de Luudens','Mago'),
('3118.png', 'Malignidad','Mago'),
('3004.png', 'Manamune','Tirador'),
('3156.png', 'Fauces del Malmortius','Tirador'),
('3041.png', 'Robaalmas de Mejai','Mago'),
('3139.png', 'Cimitarra mercurial','Tirador'),
('3222.png', 'Bendicion del Mikael','Soporte'),
('6617.png', 'Renovacion de piedra lunar','Soporte'),
('3165.png', 'Morellonomicon','Mago'),
('3033.png', 'Recordatorio Letal','Tirador'),
('3042.png', 'Muramana','Tirador'),
('3115.png', 'Diente de Nashor','Tirador'),
('6675.png', 'Filo veloz de Navori','Tirador'),
('6701.png', 'Certeza','Asesino'),
('3046.png', 'Bailarin espectral','Tirador'),
('6698.png', 'Hidra profana','Bruiser'),
('3089.png', 'Sombrero Mortal de Rabadon','Mago'),
('3143.png', 'Presagio de Randuin','Tanque'),
('3094.png', 'Cañon de fuego rapido','Tirador'),
('3074.png', 'Hidra voraz','Bruiser'),
('3107.png', 'Redencion','Soporte'),
('4633.png', 'Creagrietas','Mago'),
('6657.png', 'Vara de las edades','Mago'),
('3085.png', 'Huracan de Runaan','Tirador'),
('3116.png', 'Cetro de cristal de Rylai','Mago'),
('6695.png', 'Colmillo de serpiente','Asesino'),
('6694.png', 'Rencor de Serylda','Asesino'),
('4645.png', 'Llamasombria','Mago'),
('2065.png', 'Cancion de batalla de Shurelia','Soporte'),
('3876.png', 'Trineo del solsticio','Soporte'),
('3161.png', 'Determinacion de Shojin','Bruiser'),
('3065.png', 'Rostro espiritual','Tanque'),
('6616.png', 'Baston de aguas fluidas','Soporte'),
('3087.png', 'Puñal de static','Tirador'),
('3053.png', 'Calibrador de Sterak','Tanque'),
('3095.png', 'Navaja de asalto','Tirador'),
('4646.png', 'Sobrecarga tormentosa','Mago'),
('6631.png', 'Cortasendas','Bruiser'),
('6610.png', 'Caida celestial','Bruiser'),
('3068.png', 'Egida de fuego solar','Tanque'),
('3131.png', 'Espada de los dioses','Bruiser'),
('3302.png', 'El final','Bruiser'),
('6676.png', 'Recaudadora','Asesino'),
('3075.png', 'Malla de espinas','Tanque'),
('3748.png', 'Hidra titanica','Bruiser'),
('3002.png', 'Marcasendas','Soporte'),
('3078.png', 'Trinidad','Bruiser'),
('3179.png', 'Guja sombria','Asesino'),
('2502.png', 'Desesperanza eterna','Tanque'),
('4643.png', 'Piedra de vision vigilante','Soporte'),
('3135.png', 'Baston del vacio','Mago'),
('6699.png', 'Espada voltaica','Asesino'),
('3083.png', 'Armadura de Warmog','Tanque'),
('3119.png', 'Llegada del invierno','Tanque'),
('3091.png', 'Final del ingenio','Bruiser'),
('3142.png', 'Filo fantasmal de Youmuu','Asesino'),
('3871.png', 'Perforaplanos de ZacZac','Soporte'),
('3050.png', 'Convergencia de Zeke','Soporte'),
('3172.png', 'Cefiro','Bruiser'),
('3157.png', 'Reloj de arena de Zhonias','Mago');
